//
// Created by eliana on 20/10/19.
//

#ifndef MICROMACHINES_PLUGIN_DECREASEVELOCITY_H
#define MICROMACHINES_PLUGIN_DECREASEVELOCITY_H


class Plugin_DecreaseVelocity {

};


#endif //MICROMACHINES_PLUGIN_DECREASEVELOCITY_H
