
#ifndef MICROMACHINES_CONSTANTS_H
#define MICROMACHINES_CONSTANTS_H

#define SERIALIZING_RESCAILING 1000
#define CREATE_MATCH_MSG "create"
#define JOIN_MATCH "join"
#define VALID 0
#define MATCH_HAS_STARTED 1
#define MATCH_EQUAL_NAMED 2
#define CLIENT_EQUAL_NAMED 3

#endif //MICROMACHINES_CONSTANTS_H
