
#ifndef MICROMACHINES_CONSTANTS_H
#define MICROMACHINES_CONSTANTS_H

//sv-utils
#define FPS "framesPerSecond"
#define QUIT_ACTION 'Q'

//protocol client-sv
#define SERIALIZING_RESCAILING 1000
#define CREATE_MATCH_MSG "create"
#define VALID 0
#define MATCH_HAS_STARTED 1
#define MATCH_EQUAL_NAMED 2
#define CLIENT_EQUAL_NAMED 3

//track shapes
#define HORIZONTAL_TRACK 1
#define VERTICAL_TRACK 2
#define FIRST_QUADRANT_TRACK 3
#define SECOND_QUADRANT_TRACK 4
#define THIRD_QUADRANT_TRACK 5
#define FOURTH_QUADRANT_TRACK 4

#endif //MICROMACHINES_CONSTANTS_H
