#ifndef MICROMACHINES_IDENTIFIERS_H
#define MICROMACHINES_IDENTIFIERS_H

enum FloorId {
    GRASS_TILE,
    THIRD_QUAD_TRACK,
    SECOND_QUAD_TRACK,
    FOURTH_QUAD_TRACK,
    FIRST_QUAD_TRACK,
    LEFT_TRACK,
    RIGHT_TRACK,
    UP_TRACK,
    DOWN_TRACK,
    LEFT_WITH_CHECKPOINT_TRACK,
    RIGHT_WITH_CHECKPOINT_TRACK,
    UP_WITH_CHECKPOINT_TRACK,
    DOWN_WITH_CHECKPOINT_TRACK,
    DOWN_WITH_POSITIONS_TRACK,
    DOWN_WITH_FLAG_TRACK
};

enum EntityIdentifier {
    HEALTHBOOSTER,
    OIL,
    SPEEDBOOSTER,
    STONE,
    MUD,
    TRACK,
    GRASS,
    CAR,
    CHECKPOINT,
    GRANDSTAND
};

enum EntityStatus {
    RECENTLY_THROWN,
    ALIVE,
    DEAD
};

#endif //MICROMACHINES_IDENTIFIERS_H
